/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  documentation: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'documentation/getting-started/introduction/index',
        'documentation/getting-started/installation/index',
        'documentation/getting-started/what-is-an-observable/index',
        'documentation/getting-started/basic-built-in-observables/index',
        'documentation/getting-started/combine-observables-together/index',
        'documentation/getting-started/what-is-an-observable-pipe/index',
        'documentation/getting-started/basic-built-in-observable-pipes/index',
        'documentation/getting-started/what-is-a-source/index',
        'documentation/getting-started/what-is-a-notification/index',
        'documentation/getting-started/what-is-next/index',
      ],
    },
    'documentation/example/index',
    'documentation/naming-convention/index',
    'documentation/decision-tree/index',
    {
      type: 'category',
      label: 'Signals',
      items: [
        'documentation/signals/introduction/index',
        'documentation/signals/signal/index',
        'documentation/signals/computed/index',
        'documentation/signals/effect/index',
        'documentation/signals/observables-and-signals/index',
        'documentation/signals/conclusion/index',
      ],
    },
    {
      type: 'category',
      label: 'Migration',
      items: [
        'documentation/migration/from-promise/index',
        'documentation/migration/from-rxjs/index',
      ],
    },
    'documentation/performances/index',
    {
      type: 'link',
      href: 'https://stackblitz.com/edit/typescript-5ksaqe?devToolsHeight=33&file=index.ts',
      label: 'Playground',
    },
  ],
  reference: [
    {
      type: 'autogenerated',
      dirName: 'reference'
    },
    // {
    //   type: 'category',
    //   label: 'Alternatives',
    //   items: [
    //     {
    //       type: 'ref',
    //       id: 'reference/pipe-observable/index',
    //       label: 'pipe$$',
    //     },
    //   ],
    // },
  ],
  changelogs: [
    {
      type: 'autogenerated',
      dirName: 'changelogs'
    },
  ],
};

module.exports = sidebars;
