import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentation: [
    {
      type: 'category',
      label: 'Getting Started',
      items: [
        'documentation/getting-started/introduction/index',
        'documentation/getting-started/installation/index',
        'documentation/getting-started/reactive-programming/index',
      ],
    },
    {
      type: 'category',
      label: 'Signals',
      items: [
        'documentation/signals/introduction/index',
        'documentation/signals/signal/index',
        'documentation/signals/computed/index',
        'documentation/signals/effect/index',
        'documentation/signals/observables-and-signals/index',
        'documentation/signals/conclusion/index',
        'documentation/signals/notes/index',
      ],
    },
    {
      type: 'category',
      label: 'Observables',
      items: [
        'documentation/observables/introduction/index',
        'documentation/observables/what-is-an-observable/index',
        'documentation/observables/basic-built-in-observables/index',
        'documentation/observables/combine-observables-together/index',
        'documentation/observables/what-is-an-observable-pipe/index',
        'documentation/observables/basic-built-in-observable-pipes/index',
        'documentation/observables/what-is-a-source/index',
        'documentation/observables/what-is-a-notification/index',
        'documentation/observables/example/index',
        'documentation/observables/naming-convention/index',
        'documentation/observables/what-is-next/index',
      ],
    },
    'documentation/decision-tree/index',
    {
      type: 'category',
      label: 'Migration',
      items: [
        'documentation/migration/from-promise/index',
        'documentation/migration/from-rxjs/index',
      ],
    },
    {
      type: 'category',
      label: 'Performances',
      items: [
        'documentation/performances/introduction/index',
        'documentation/performances/vs-rxjs/index',
        'documentation/performances/vs-angular/index',
      ],
    },
    {
      type: 'link',
      href: 'https://stackblitz.com/edit/typescript-5ksaqe?devToolsHeight=33&file=index.ts',
      label: 'Playground',
    },
  ],
  reference: [
    {
      type: 'autogenerated',
      dirName: 'reference',
    },
    // {
    //   type: 'category',
    //   label: 'Alternatives',
    //   items: [
    //     {
    //       type: 'ref',
    //       id: 'reference/pipe-observable/index',
    //       label: 'pipe$$',
    //     },
    //   ],
    // },
  ],
  changelogs: [
    {
      type: 'autogenerated',
      dirName: 'changelogs',
    },
  ],
};

export default sidebars;
